name: Scrape latest spills data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '7,27,47 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        curl https://www.southernwater.co.uk/gateway/Beachbuoy/1.0/api/v1.0/Spills | jq . > spills.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest spills data: ${timestamp}" || exit 0
        git push
